<?php
/**
 * @file
 * Contains install and update functions for Context Block Visibility.
 */

/**
 * Implements hook_schema().
 */
function midtlink_unit_block_visibility_schema() {
  $schema['midtlink_unit_block_visibility'] = array(
    'description' => 'Sets up access permissions for blocks based on user contexts',
    'fields' => array(
      'module' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => TRUE,
        'description' => "The block's origin module, from {block}.module.",
      ),
      'delta' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'description' => "The block's unique delta within module, from {block}.delta.",
      ),
      'context' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => "The context",
      ),
    ),
    'primary key' => array('module', 'delta', 'context'),
    'indexes' => array(
      'rid' => array('context'),
    ),
  );
  return $schema;
}
